#!/bin/sh

CCVER=${CCVER:-"echo version number unknown -- check IRIX version"}

MD_LIBS=${MD_LIBS:--lmpi}
START_MD_LIBS=${START_MD_LIBS:-""}

. $ZPLHOME/etc/mpi/Macros

CFLAGS="$CFLAGS -64"
START_CFLAGS="$START_CFLAGS -64"
LFLAGS="$LFLAGS -64"
START_LFLAGS="$START_LFLAGS -64"
