include ../Makefile.header

SRC= contraction.c copts.c deadvarelim.c dvlist.c floodopt.c floodtile.c ntablet.c nudge.c runtime_checks.c stencil.c strength.c permcomm.c
OBJ= $(SRC:.c=.o)

include ../Makefile.base
