include ../Makefile.header

SRC= Agen.c Bgen.c Cgen.c Dgen.c Dgenhelp.c Fgen.c IOgen.c Irongen.c\
	Mgen.c Privgen.c Profgen.c Redgen.c \
	Repgen.c SRgen.c Scangen.c Spsgen.c Stackgen.c Wgen.c WRgen.c \
	beautify.c cmplx_ens.c checkpoint.c
OBJ= $(SRC:.c=.o)

include ../Makefile.base
