#!/bin/csh -f
#
# make pvm up to date
#

# setenv XXX_OLD_ZPLCOMMLAYER \$ZPLCOMMLAYER

setenv ZPLCOMMLAYER pvm
./zmake clean
cd pvm
./zmake clean
./zmake "CFLAGS=-g"
cd ..
./zmake "CFLAGS=-g"

# setenv ZPLCOMMLAYER \$XXX_OLD_ZPLCOMMLAYER
# unsetenv XXX_OLD_ZPLCOMMLAYER
