#!/bin/csh -f
#
# make mpi up to date
#

# setenv XXX_OLD_ZPLCOMMLAYER \$ZPLCOMMLAYER

setenv ZPLCOMMLAYER mpi
./zmake clean
cd mpi
./zmake clean
./zmake "CFLAGS=-g"
cd ..
./zmake "CFLAGS=-g"

# setenv ZPLCOMMLAYER \$XXX_OLD_ZPLCOMMLAYER
# unsetenv XXX_OLD_ZPLCOMMLAYER
