include ../Makefile.header

SRC= alias.c coverage.c datatype.c dimension.c expr.c function.c init.c\
	mloop.c statement.c rmstack.c scale.c symboltable.c zutil.c
OBJ= $(SRC:.c=.o)

include ../Makefile.base
